spring:
  datasource:
    url: jdbc:sqlite:project2.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update # Sửa đổi từ 'create' thành 'update'
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: never # Sửa đổi từ 'always' thành 'never'
